### ISSUE TITLE
Path with – character gets interpreted as � when opening a model 

### ISSUE THREAD

**Issue by Droooga** [SamVanheer/HalfLifeAssetManager#271]
– is the character Windows assigns by default to copied folders and such. I rather have this fixed than break all the filepaths to that model's sources. 1.3.0 version didn't have this issue though.
![kuva](https://user-images.githubusercontent.com/85588460/215551414-c9edd676-4704-4d1c-8c74-8b5a1b51391a.png)

**Comment by SamVanheer** [comment]
Thanks, i missed one case where paths aren't converted correctly and this caused the regression.

You can try out the fix using the automated build downloadable from this page once the build has completed: https://github.com/SamVanheer/HalfLifeAssetManager/actions/runs/4055454914

Let me know if it works for you or not.
