### ISSUE TITLE
Can not open .mdl files from explorer

### ISSUE THREAD

**Issue by Bluesed** [SamVanheer/HalfLifeAssetManager#282]
As the title says, in Windows 11, when I double-click a .mdl file. It might be an issue with Windows but I can't figure out what is. I have associated .mdl files with HLAM but still not working.
[HLAM-Log.txt](https://github.com/SamVanheer/HalfLifeAssetManager/files/13392307/HLAM-Log.txt)

**Comment by SamVanheer** [comment]
The latest beta installer was created using Qt installer 4.6, looks like previous versions silently ignored a problem with the file association setup. I've fixed it so it should work again.

**Comment by SamVanheer** [comment]
Beta 12 has been released and should fix this problem.
