### ISSUE TITLE
No permissions 

### ISSUE THREAD

**Issue by Bluesed** [SamVanheer/HalfLifeAssetManager#283]
C:\Program Files (x86)\Steam\steamapps\common\Half-Life\czero_downloads\models\cs_thera ...
Windows cannot access the specified device, path, or file. You may not have the appropriate
permissions to access the item.

This might just be me who is not used to this kind of messages, and I just have to figure out how to give HLAM.exe permissions but if you know how to solve it let me know and if it's just me and windows then you can just tell me its windows problem and I will try to google myself.

World has bigger problems like hl1 not working and what to do with Gaza and Israel so just ignore me if it is too much.

**Comment by SamVanheer** [comment]
Which beta are you trying to use? Beta 12 was released yesterday and should fix this.

**Comment by SamVanheer** [comment]
Also note that the installer is responsible for setting up file associations. If you installed it that way and then copy pasted the portable version on top it'll still use the associations set up by the installer, and that's what was broken.

Install beta 12 with the installer and let me know if it works.

**Comment by Bluesed** [comment]
Here are the answers that I got from gpt4 and none of them made any difference :( (FUCK AI - useless to solve real problems xD)

1 Change the file permission: Right-click the file, choose Properties, go to the Security tab, and edit the user name and group

2 Unblock the file: Right-click the file, choose Properties, and check the Unblock option

3 Turn off antivirus or firewall temporarily

*Other answers are excluded as worthless in this specific case.

**Comment by SamVanheer** [comment]
Try adding HLAM to your antivirus' exclusions list: https://old.reddit.com/r/techsupport/comments/mlgpb3/windows_cannot_access_the_specified_device_path/

**Comment by Bluesed** [comment]
Thanks. I tried adding .mdl files to exclusions, HLAM, and folders, and turning off all Windows security and nothing changed.  Still open to more solutions if you have any.

**Comment by Bluesed** [comment]
I solved it! Was not permissions was the associated program that I believe was still referring to the first installation of HLAM 1. x. 
WIN11 - Settings - Apps - Default Apps - "reselect HLAM" :)
I shall close this comment and thank you for your support and efforts in making great tools !!!

**Comment by SamVanheer** [comment]
Good to hear, thanks for letting me know.
