### ISSUE TITLE
.deb packagings?

### ISSUE THREAD

**Issue by MesaBlack** [SamVanheer/HalfLifeAssetManager#284]
Add a .deb package, with desktop/start menu shortcut if possible.

**Comment by SamVanheer** [comment]
When there is a Linux version i'll look into providing a deb package. There is no Linux version yet since there are graphical issues. Those will be fixed in version 3.

**Comment by MesaBlack** [comment]
a'ight

**Comment by pseiler** [comment]
A linux version would be awesome. Looking forward to it. I could create some RPM and archlinux packages

**Comment by SamVanheer** [comment]
I've set up everything needed to make Debian packages. Once i've wrapped up a couple other things i can make a first beta build for testing.

To keep all Linux-related issues in one place, please direct all feedback to issue #10.
