### ISSUE TITLE
The model is displayed in a small area of the HLAM window (Linux, Wayland)

### ISSUE THREAD

**Issue by Nord1cWarr1or** [SamVanheer/HalfLifeAssetManager#291]
### Description
The model viewing window only occupies a quarter of the program window. This happens when viewing any model, regardless of the window size, whether it is stretched across the entire screen or not.
- **The issue does not occur when using the X11 graphics server.**

### Steps to Reproduce
1. Start the Linux distribution with the Wayland protocol.
2. Open HLAM.
3. Open any model.

### Expected Result
The model should be displayed in the entire viewing area.

### Actual Result
The model is displayed in approximately 1/4 of the viewing area.

### Environment
OS: [Garuda Linux](https://garudalinux.org/) Dr460nized edition - Arch-based distro, native installed.
Desktop Environment: KDE Plasma 6.0.2
Graphics Server: Wayland
GPU: NVIDIA RTX 3070Ti
OpenGL: `OpenGL version string: 4.6.0 NVIDIA 550.54.14`

### Additional Information
<details>
  <summary>Screenshots</summary>

  ![image](https://github.com/SamVanheer/HalfLifeAssetManager/assets/47604048/35c426f7-993d-4ea0-ad9d-76ed3f88204a)

  ![image](https://github.com/SamVanheer/HalfLifeAssetManager/assets/47604048/7596dd63-83e3-4323-a10f-db110f9b0682) 
</details>

Logs: [HLAM-Log.txt](https://github.com/SamVanheer/HalfLifeAssetManager/files/14646085/HLAM-Log.txt)

**Comment by SamVanheer** [comment]
Can you provide more information about your system specs? Which distro and version, is it a native install or running in a virtual machine, what graphics card do you have, what's your OpenGL driver, does this happen with every model, does it happen when the window isn't stretched so much?

Provide as much information as you can.

**Comment by SamVanheer** [comment]
Also enable OpenGL logging and check what the output is: https://github.com/SamVanheer/HalfLifeAssetManager/blob/master/docs/manual/HalfLifeAssetManagerManual.md#5-configuring-log-output

**Comment by Nord1cWarr1or** [comment]
> Can you provide more information about your system specs? Which distro and version, is it a native install or running in a virtual machine, what graphics card do you have, what's your OpenGL driver, does this happen with every model, does it happen when the window isn't stretched so much?
> 
> Provide as much information as you can.

I've updated my first post adding detailed information

**Comment by SamVanheer** [comment]
I checked this out and it looks like it's a bug in the Qt Wayland platform plugin. All of the logic involving window size is correct and uses the same size information used in Qt's official examples.

I was able to replicate the same behavior by interpreting window size as half what it actually is, which means somewhere along the line Qt is getting the actual window size and halving it for some reason.

Notably running it using Wayland in an Ubuntu virtual machine works as it should so this may be specific to the distro, but i have no way of investigating this further.

This program is using Qt5 so it's possible that it is fixed in Qt6 but upgrading to that is not an option at this time since that would involve dropping support for Windows 7 and 8.1.

You'll have to run it using X11 instead.

**Comment by Nord1cWarr1or** [comment]
> Notably running it using Wayland in an Ubuntu virtual machine works as it should so this may be specific to the distro, but i have no way of investigating this further.

Hmm, that's really weird. I checked on another distro, [EndeavourOS](https://endeavouros.com/), on which I also use Plasma 6.0.2 and Wayland, and it doesn't have this problem.

**Comment by SamVanheer** [comment]
I've added instructions to the readme and manual about using X11 if Wayland doesn't work.

Judging by the number of bug reports on the Qt issue tracker about bugs involving Wayland and OpenGL this is probably not an isolated problem but there's nothing that can be done about it in this program, so i'm closing this issue.
