### ISSUE TITLE
.mdl file association not working on Windows 11

### ISSUE THREAD

**Issue by Mystyle-48** [SamVanheer/HalfLifeAssetManager#292]
On my Windows 11 machine, attempting to open a `.mdl` file from the explorer does not work.

Viewing the "Open with" entry for HLAM in OpenWithView reveals that the file path is `C:\Windows\system32\C:/Program Files (x86)/Half-Life Asset Manager/HLAM.exe`, which causes the file association to fail:

![image](https://github.com/SamVanheer/HalfLifeAssetManager/assets/89315313/088a0974-9db2-4578-9a38-db57f8bf1740)

I have no idea where the system32 part comes from, as I installed the program normally with the offline installer.

Installation log file:
[InstallationLog.txt](https://github.com/SamVanheer/HalfLifeAssetManager/files/14661556/InstallationLog.txt)

**Comment by SamVanheer** [comment]
Thanks for reporting this. It turns out that the Qt installer framework doesn't convert slashes to backslashes on Windows and this causes Explorer to get confused. It should work properly starting with the next release.
